/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photonvision_raspi_PicamJNI */

#ifndef _Included_org_photonvision_raspi_PicamJNI
#define _Included_org_photonvision_raspi_PicamJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    createCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_photonvision_raspi_PicamJNI_createCamera
  (JNIEnv *, jobject);

/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    destroyCamera
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_photonvision_raspi_PicamJNI_destroyCamera
  (JNIEnv *, jobject);

/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    setExposure
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_photonvision_raspi_PicamJNI_setExposure
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    setBrightness
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_photonvision_raspi_PicamJNI_setBrightness
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    setISO
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_photonvision_raspi_PicamJNI_setISO
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    setRotation
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_photonvision_raspi_PicamJNI_setRotation
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    setVideoMode
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_org_photonvision_raspi_PicamJNI_setVideoMode
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    grabFrame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_photonvision_raspi_PicamJNI_grabFrame
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
