/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_photonvision_raspi_PicamJNI */

#ifndef _Included_org_photonvision_raspi_PicamJNI
#define _Included_org_photonvision_raspi_PicamJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_photonvision_raspi_PicamJNI
 * Method:    createCamera
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_photonvision_raspi_PicamJNI_createCamera
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
